In [2]:
import numpy as np
import pandas as pd

# Setting a Time Index in Pandas

In [3]:
df = pd.read_csv("D:/Complete ML/Time Series Data/1-Time-series-analysis/sales.csv")
df.head()

         date  sales
0  2022-01-01   1200
1  2022-01-02    980
2  2022-01-03   1100
3  2022-01-04    870
4  2022-01-05    760

In [4]:
df.shape

(365, 2)

In [5]:
# Convert the date column to datetime and set as index
df["date"] = pd.to_datetime(df["date"])
df.set_index("date", inplace=True)

In [6]:
df.head()

            sales
date
2022-01-01   1200
2022-01-02    980
2022-01-03   1100
2022-01-04    870
2022-01-05    760

# Resampling - Changing Frequency

In [7]:
# Downsampling (going to lower frequency)
monthly_sales_total = df["sales"].resample("MS").sum()    # Total sales per month
monthly_sales_avg = df["sales"].resample("MS").mean()     # Monthly average of sales

print(monthly_sales_total)
print("-"*40)
print(monthly_sales_avg)

date
2022-01-01    36980
2022-02-01    35520
2022-03-01    42510
2022-04-01    48200
2022-05-01    54370
2022-06-01    57850
2022-07-01    67260
2022-08-01    71480
2022-09-01    75530
2022-10-01    84080
2022-11-01    87550
2022-12-01    98420
Freq: MS, Name: sales, dtype: int64
----------------------------------------
date
2022-01-01    1192.903226
2022-02-01    1268.571429
2022-03-01    1371.290323
2022-04-01    1606.666667
2022-05-01    1753.870968
2022-06-01    1928.333333
2022-07-01    2169.677419
2022-08-01    2305.806452
2022-09-01    2517.666667
2022-10-01    2712.258065
2022-11-01    2918.333333
2022-12-01    3174.838710
Freq: MS, Name: sales, dtype: float64

In [8]:
df.head()

            sales
date
2022-01-01   1200
2022-01-02    980
2022-01-03   1100
2022-01-04    870
2022-01-05    760

In [9]:
# Upsampling (going to higher frequency)
daily1 = df["sales"].resample("D").ffill()  # Forward fill
daily2 = df["sales"].resample("D").interpolate()    # Linear Interpolation

print(daily1)
print("-" * 40)
print(daily2)

date
2022-01-01    1200
2022-01-02     980
2022-01-03    1100
2022-01-04     870
2022-01-05     760
              ...
2022-12-27    2960
2022-12-28    3000
2022-12-29    3200
2022-12-30    3500
2022-12-31    3800
Freq: D, Name: sales, Length: 365, dtype: int64
----------------------------------------
date
2022-01-01    1200
2022-01-02     980
2022-01-03    1100
2022-01-04     870
2022-01-05     760
              ...
2022-12-27    2960
2022-12-28    3000
2022-12-29    3200
2022-12-30    3500
2022-12-31    3800
Freq: D, Name: sales, Length: 365, dtype: int64

### Forward Fill
##### The idea: "I dont know what happened after this point, so I'll assume it stayed the same until the next known value". It takes the last known value and carries it forward to fill all the gaps

In [10]:
df.head()

            sales
date
2022-01-01   1200
2022-01-02    980
2022-01-03   1100
2022-01-04    870
2022-01-05    760

In [11]:
# Step 1: Downsample to monthly (sum of sales per month)
monthly = df["sales"].resample("MS").sum()
print("First 6 rows of monthly data")
print("-" * 40)
print(monthly.head(6))

First 6 rows of monthly data
----------------------------------------
date
2022-01-01    36980
2022-02-01    35520
2022-03-01    42510
2022-04-01    48200
2022-05-01    54370
2022-06-01    57850
Freq: MS, Name: sales, dtype: int64

In [12]:
# Step 2: Upsample back to daily using forward fill
daily_forward_fill = monthly.resample("D").ffill()
print("After ffill to daily")
print("-" * 40)
print(daily_forward_fill.head(35))

After ffill to daily
----------------------------------------
date
2022-01-01    36980
2022-01-02    36980
2022-01-03    36980
2022-01-04    36980
2022-01-05    36980
2022-01-06    36980
2022-01-07    36980
2022-01-08    36980
2022-01-09    36980
2022-01-10    36980
2022-01-11    36980
2022-01-12    36980
2022-01-13    36980
2022-01-14    36980
2022-01-15    36980
2022-01-16    36980
2022-01-17    36980
2022-01-18    36980
2022-01-19    36980
2022-01-20    36980
2022-01-21    36980
2022-01-22    36980
2022-01-23    36980
2022-01-24    36980
2022-01-25    36980
2022-01-26    36980
2022-01-27    36980
2022-01-28    36980
2022-01-29    36980
2022-01-30    36980
2022-01-31    36980
2022-02-01    35520
2022-02-02    35520
2022-02-03    35520
2022-02-04    35520
Freq: D, Name: sales, dtype: int64

### Interpolation
##### The idea: "I know the value at point A and point B, so I will draw a straight line between them and estimate values in between". It fills gaps by calculating what the value would be if it changed smoothly and linearly from one known point to the next

In [13]:
monthly_sales_total

date
2022-01-01    36980
2022-02-01    35520
2022-03-01    42510
2022-04-01    48200
2022-05-01    54370
2022-06-01    57850
2022-07-01    67260
2022-08-01    71480
2022-09-01    75530
2022-10-01    84080
2022-11-01    87550
2022-12-01    98420
Freq: MS, Name: sales, dtype: int64

In [14]:
# Now fill this with interpolation
daily_interpolation = monthly.resample("D").interpolate()
print("After interpolation to daily")
print("-" * 40)
print(daily_interpolation.head(35))

After interpolation to daily
----------------------------------------
date
2022-01-01    36980.000000
2022-01-02    36932.903226
2022-01-03    36885.806452
2022-01-04    36838.709677
2022-01-05    36791.612903
2022-01-06    36744.516129
2022-01-07    36697.419355
2022-01-08    36650.322581
2022-01-09    36603.225806
2022-01-10    36556.129032
2022-01-11    36509.032258
2022-01-12    36461.935484
2022-01-13    36414.838710
2022-01-14    36367.741935
2022-01-15    36320.645161
2022-01-16    36273.548387
2022-01-17    36226.451613
2022-01-18    36179.354839
2022-01-19    36132.258065
2022-01-20    36085.161290
2022-01-21    36038.064516
2022-01-22    35990.967742
2022-01-23    35943.870968
2022-01-24    35896.774194
2022-01-25    35849.677419
2022-01-26    35802.580645
2022-01-27    35755.483871
2022-01-28    35708.387097
2022-01-29    35661.290323
2022-01-30    35614.193548
2022-01-31    35567.096774
2022-02-01    35520.000000
2022-02-02    35769.642857
2022-02-03    36019.285714
2022-02-04    36268.928571
Freq: D, Name: sales, dtype: float64