# Feature Engineering for ML models

In [27]:
import numpy as np
import pandas as pd

In [28]:
df = pd.read_csv("sales.csv")
df["date"] = pd.to_datetime(df["date"])
df.set_index("date", inplace=True)

In [29]:
df.head()

            sales
date
2022-01-01   1200
2022-01-02    980
2022-01-03   1100
2022-01-04    870
2022-01-05    760

In [30]:
# Rolling mean — captures recent trend/level
df["roll_mean_7"] = df["sales"].rolling(window=7).mean()
df["roll_mean_30"] = df["sales"].rolling(window=30).mean()

In [31]:
df.head(15)

            sales  roll_mean_7  roll_mean_30
date
2022-01-01   1200          NaN           NaN
2022-01-02    980          NaN           NaN
2022-01-03   1100          NaN           NaN
2022-01-04    870          NaN           NaN
2022-01-05    760          NaN           NaN
2022-01-06   1450          NaN           NaN
2022-01-07   1600  1137.142857           NaN
2022-01-08   1150  1130.000000           NaN
2022-01-09   1020  1135.714286           NaN
2022-01-10   1080  1132.857143           NaN
2022-01-11    930  1141.428571           NaN
2022-01-12    850  1154.285714           NaN
2022-01-13   1520  1164.285714           NaN
2022-01-14   1650  1171.428571           NaN
2022-01-15   1180  1175.714286           NaN

In [32]:
# Rolling std — captures recent volatility
df["roll_std_7"] = df["sales"].rolling(window=7).std()

In [33]:
df.head(15)

            sales  roll_mean_7  roll_mean_30  roll_std_7
date
2022-01-01   1200          NaN           NaN         NaN
2022-01-02    980          NaN           NaN         NaN
2022-01-03   1100          NaN           NaN         NaN
2022-01-04    870          NaN           NaN         NaN
2022-01-05    760          NaN           NaN         NaN
2022-01-06   1450          NaN           NaN         NaN
2022-01-07   1600  1137.142857           NaN  304.341600
2022-01-08   1150  1130.000000           NaN  303.205101
2022-01-09   1020  1135.714286           NaN  300.269720
2022-01-10   1080  1132.857143           NaN  300.760940
2022-01-11    930  1141.428571           NaN  292.770022
2022-01-12    850  1154.285714           NaN  274.642625
2022-01-13   1520  1164.285714           NaN  288.146788
2022-01-14   1650  1171.428571           NaN  301.077430
2022-01-15   1180  1175.714286           NaN  300.935051

In [34]:
# Rolling min and max — capture recent range
df['roll_min_7']   = df['sales'].rolling(window=7).min()
df['roll_max_7']   = df['sales'].rolling(window=7).max()

In [35]:
df.head(15)

,sales,roll_mean_7,roll_mean_30,roll_std_7,roll_min_7,roll_max_7
date,,,,,,
2022-01-01,1200,NaN,NaN,NaN,NaN,NaN
2022-01-02,980,NaN,NaN,NaN,NaN,NaN
2022-01-03,1100,NaN,NaN,NaN,NaN,NaN
2022-01-04,870,NaN,NaN,NaN,NaN,NaN
2022-01-05,760,NaN,NaN,NaN,NaN,NaN
2022-01-06,1450,NaN,NaN,NaN,NaN,NaN
2022-01-07,1600,1137.142857,NaN,304.341600,760.0,1600.0
2022-01-08,1150,1130.000000,NaN,303.205101,760.0,1600.0
2022-01-09,1020,1135.714286,NaN,300.269720,760.0,1600.0
2022-01-10,1080,1132.857143,NaN,300.760940,760.0,1600.0
2022-01-11,930,1141.428571,NaN,292.770022,760.0,1600.0
2022-01-12,850,1154.285714,NaN,274.642625,850.0,1600.0
2022-01-13,1520,1164.285714,NaN,288.146788,850.0,1600.0
2022-01-14,1650,1171.428571,NaN,301.077430,850.0,1650.0
2022-01-15,1180,1175.714286,NaN,300.935051,850.0,1650.0

In [36]:
# Rolling median — robust to outliers, unlike mean
df['roll_median_7'] = df['sales'].rolling(window=7).median()

In [37]:
df.head(15)

,sales,roll_mean_7,roll_mean_30,roll_std_7,roll_min_7,roll_max_7,roll_median_7
date,,,,,,,
2022-01-01,1200,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-02,980,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-03,1100,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-04,870,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-05,760,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-06,1450,NaN,NaN,NaN,NaN,NaN,NaN
2022-01-07,1600,1137.142857,NaN,304.341600,760.0,1600.0,1100.0
2022-01-08,1150,1130.000000,NaN,303.205101,760.0,1600.0,1100.0
2022-01-09,1020,1135.714286,NaN,300.269720,760.0,1600.0,1100.0
2022-01-10,1080,1132.857143,NaN,300.760940,760.0,1600.0,1080.0
2022-01-11,930,1141.428571,NaN,292.770022,760.0,1600.0,1080.0
2022-01-12,850,1154.285714,NaN,274.642625,850.0,1600.0,1080.0
2022-01-13,1520,1164.285714,NaN,288.146788,850.0,1600.0,1080.0
2022-01-14,1650,1171.428571,NaN,301.077430,850.0,1650.0,1080.0
2022-01-15,1180,1175.714286,NaN,300.935051,850.0,1650.0,1080.0